# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='popular',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
